Refactored code
vasanex/ItemQuickSwitchMod pull request #1
Opened 2023-11-19 04:32 UTC by MarkdeGraaff

Made the code a bit shorter and used some newer C# stuff like C# 8.0 Null Coalescing Assignment.

2023-11-19 23:49 UTC, vasanex requested changes
Hi, first of all thank you for this pull request, it contains loads of good changes that I'd love to include. 

In addition to my comments, can you please fix the following things before I merge:

* If possible please rebase on the current main branch as there are some conflicts due me pushing commits.
* There are some Visual Studio specific binary files in your commit that are not needed, this should be fixed automatically after rebase since I've updated the gitignore.

2023-11-19 23:49 UTC, vasanex commented on ItemQuickSwitchMod/ItemQuickSwitchMod.csproj
The changes in this file can be excluded from the PR commit, I think.

I will also add a `csproj.user` file later so that paths to assemblies are not hardcoded in here.

2023-11-19 23:49 UTC, vasanex commented on ItemQuickSwitchMod/Patches/PlayerControllerBPatch.cs
> +                instance.mls.LogInfo("Player is dancing now.");
I removed the log statements here in a later commit because frankly they are not needed for the players and were mainly used by myself during development.

2023-11-20 09:22 UTC, MarkdeGraaff commented
Made changes requested.

2023-11-20 10:08 UTC, merged